export const CONNECTIVITY_STATUS_DEBOUNCE_MS = 3_000;

export const ADVANCED_OPERATION_POLL_INTERVAL_MS = 3_000;
export const ADVANCED_OPERATION_START_TIMEOUT_MS = 120_000;
export const ADVANCED_OPERATION_STATUS_TIMEOUT_MS = 30_000;
export const ADVANCED_OPERATION_ANALYSIS_TIMEOUT_MS = 300_000;
export const ADVANCED_OFDMA_PRE_EQ_ANALYSIS_TIMEOUT_MS = ADVANCED_OPERATION_ANALYSIS_TIMEOUT_MS;

export const LONG_RUNNING_OPERATION_TIMEOUT_MS = 90_000;

export const CHART_SERIES_PALETTE = [
  "#79a9ff",
  "#58d0a7",
  "#ef4444",
  "#f59e0b",
  "#a78bfa",
] as const;

export const CHART_SERIES_PALETTE_SIZE = CHART_SERIES_PALETTE.length;
