export const requestFieldHints = {
  mac_address: "Cable modem MAC address.",
  ip_address: "Reachable IPv4 address of the cable modem.",
  tftp_ipv4: "IPv4 address of the TFTP server used for capture retrieval.",
  tftp_ipv6: "IPv6 address of the TFTP server used for capture retrieval.",
  channel_ids: "0 means all channels.",
  snmp_rw_community: "SNMP read-write community string used for the request.",
  sample_duration: "Histogram sample duration in seconds.",
  fec_summary_type: "Choose the backend FEC window to request.",
  display_cross_hair: "Show or hide the constellation cross-hair overlay.",
  modulation_order_offset: "Offset the reported modulation order when the backend supports it.",
  number_sample_symbol: "Number of constellation samples to request from the backend.",
  sample_time_elapsed: "Sampling interval in seconds used to calculate codeword error rate.",
  measurement_duration: "Total multi-capture collection time in seconds.",
  sample_interval: "Interval between captures in seconds.",
  measure_mode: "Advanced RxMER collection mode used by the backend.",
  moving_average_points: "Moving average window size used for the friendly spectrum overlay.",
  inactivity_timeout: "Maximum idle time in seconds before the spectrum capture stops.",
  first_segment_center_freq: "Requested first spectrum segment center frequency in Hz.",
  last_segment_center_freq: "Requested last spectrum segment center frequency in Hz.",
  resolution_bw: "Resolution bandwidth in Hz used to derive segment span and FFT bin count.",
  noise_bw: "Equivalent noise bandwidth in kHz.",
  window_function: "FFT window function selector used by the backend capture.",
  num_averages: "Number of averages the backend applies per segment.",
  spectrum_retrieval_type: "Spectrum retrieval mode used by the backend capture.",
  spectrum_direction: "Select whether the full-band spectrum capture resolves downstream or upstream diplexer band edges.",
  number_of_averages: "Number of samples used to calculate the spectrum average per bin.",
  resolution_bandwidth_hz: "Resolution bandwidth in Hz used for the OFDM spectrum capture.",
  operation_id: "Existing advanced operation identifier used to fetch results and run analysis without starting a new capture.",
  upload_pnm_file: "Upload accepts raw PNM capture files and registers a new transaction in PyPNM.",
  file_mac_search: "Search stored PyPNM files by cable modem MAC address.",
  direct_downloads: "Use the selected MAC archive in browse, or download directly by stored filename and operation ID here.",
  hexdump_bytes_per_line: "Number of bytes shown on each rendered hexdump line.",
} as const;
