import { cloneGenericSystemDescription } from "@/lib/pypnm/genericSystemDescription";
import type { If31DsOfdmProfileStatsResponse } from "@/types/api";

export const singleIf31DsOfdmProfileStatsFixture: If31DsOfdmProfileStatsResponse = {
  system_description: cloneGenericSystemDescription(),
  status: 0,
  message: null,
  device: {
    mac_address: "aa:bb:cc:dd:ee:ff",
    system_description: cloneGenericSystemDescription(),
  },
  results: [
    {
      index: 48,
      channel_id: 194,
      profiles: {
        "0": {
          docsIf31CmDsOfdmProfileStatsConfigChangeCt: 0,
          docsIf31CmDsOfdmProfileStatsTotalCodewords: 10993816,
          docsIf31CmDsOfdmProfileStatsCorrectedCodewords: 3915,
          docsIf31CmDsOfdmProfileStatsUncorrectableCodewords: 0,
          docsIf31CmDsOfdmProfileStatsInOctets: 4443771,
          docsIf31CmDsOfdmProfileStatsInUnicastOctets: 1397,
          docsIf31CmDsOfdmProfileStatsInMulticastOctets: 4025896,
          docsIf31CmDsOfdmProfileStatsInFrames: 69413,
          docsIf31CmDsOfdmProfileStatsInUnicastFrames: 1,
          docsIf31CmDsOfdmProfileStatsInMulticastFrames: 69412,
          docsIf31CmDsOfdmProfileStatsInFrameCrcFailures: 0,
          docsIf31CmDsOfdmProfileStatsCtrDiscontinuityTime: 0,
        },
        "3": {
          docsIf31CmDsOfdmProfileStatsConfigChangeCt: 0,
          docsIf31CmDsOfdmProfileStatsTotalCodewords: 0,
          docsIf31CmDsOfdmProfileStatsCorrectedCodewords: 0,
          docsIf31CmDsOfdmProfileStatsUncorrectableCodewords: 0,
          docsIf31CmDsOfdmProfileStatsInOctets: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInFrames: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInFrameCrcFailures: 0,
          docsIf31CmDsOfdmProfileStatsCtrDiscontinuityTime: 0,
        },
        "4": {
          docsIf31CmDsOfdmProfileStatsConfigChangeCt: 0,
          docsIf31CmDsOfdmProfileStatsTotalCodewords: 0,
          docsIf31CmDsOfdmProfileStatsCorrectedCodewords: 0,
          docsIf31CmDsOfdmProfileStatsUncorrectableCodewords: 0,
          docsIf31CmDsOfdmProfileStatsInOctets: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInFrames: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInFrameCrcFailures: 0,
          docsIf31CmDsOfdmProfileStatsCtrDiscontinuityTime: 0,
        },
        "255": {
          docsIf31CmDsOfdmProfileStatsConfigChangeCt: 0,
          docsIf31CmDsOfdmProfileStatsTotalCodewords: 211308433,
          docsIf31CmDsOfdmProfileStatsCorrectedCodewords: 0,
          docsIf31CmDsOfdmProfileStatsUncorrectableCodewords: 0,
          docsIf31CmDsOfdmProfileStatsInOctets: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInFrames: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInFrameCrcFailures: 0,
          docsIf31CmDsOfdmProfileStatsCtrDiscontinuityTime: 0,
        },
      },
    },
    {
      index: 49,
      channel_id: 193,
      profiles: {
        "0": {
          docsIf31CmDsOfdmProfileStatsConfigChangeCt: 0,
          docsIf31CmDsOfdmProfileStatsTotalCodewords: 10972110,
          docsIf31CmDsOfdmProfileStatsCorrectedCodewords: 3050,
          docsIf31CmDsOfdmProfileStatsUncorrectableCodewords: 0,
          docsIf31CmDsOfdmProfileStatsInOctets: 4444539,
          docsIf31CmDsOfdmProfileStatsInUnicastOctets: 1397,
          docsIf31CmDsOfdmProfileStatsInMulticastOctets: 4026592,
          docsIf31CmDsOfdmProfileStatsInFrames: 69425,
          docsIf31CmDsOfdmProfileStatsInUnicastFrames: 1,
          docsIf31CmDsOfdmProfileStatsInMulticastFrames: 69424,
          docsIf31CmDsOfdmProfileStatsInFrameCrcFailures: 0,
          docsIf31CmDsOfdmProfileStatsCtrDiscontinuityTime: 0,
        },
        "3": {
          docsIf31CmDsOfdmProfileStatsConfigChangeCt: 0,
          docsIf31CmDsOfdmProfileStatsTotalCodewords: 0,
          docsIf31CmDsOfdmProfileStatsCorrectedCodewords: 0,
          docsIf31CmDsOfdmProfileStatsUncorrectableCodewords: 0,
          docsIf31CmDsOfdmProfileStatsInOctets: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInFrames: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInFrameCrcFailures: 0,
          docsIf31CmDsOfdmProfileStatsCtrDiscontinuityTime: 0,
        },
        "4": {
          docsIf31CmDsOfdmProfileStatsConfigChangeCt: 0,
          docsIf31CmDsOfdmProfileStatsTotalCodewords: 0,
          docsIf31CmDsOfdmProfileStatsCorrectedCodewords: 0,
          docsIf31CmDsOfdmProfileStatsUncorrectableCodewords: 0,
          docsIf31CmDsOfdmProfileStatsInOctets: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInFrames: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInFrameCrcFailures: 0,
          docsIf31CmDsOfdmProfileStatsCtrDiscontinuityTime: 0,
        },
        "255": {
          docsIf31CmDsOfdmProfileStatsConfigChangeCt: 0,
          docsIf31CmDsOfdmProfileStatsTotalCodewords: 211334592,
          docsIf31CmDsOfdmProfileStatsCorrectedCodewords: 0,
          docsIf31CmDsOfdmProfileStatsUncorrectableCodewords: 0,
          docsIf31CmDsOfdmProfileStatsInOctets: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastOctets: 0,
          docsIf31CmDsOfdmProfileStatsInFrames: 0,
          docsIf31CmDsOfdmProfileStatsInUnicastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInMulticastFrames: 0,
          docsIf31CmDsOfdmProfileStatsInFrameCrcFailures: 0,
          docsIf31CmDsOfdmProfileStatsCtrDiscontinuityTime: 0,
        },
      },
    },
  ],
};
