import type { AtdmaChannelStatsResponse } from "@/types/api";

export const singleAtdmaChannelStatsFixture: AtdmaChannelStatsResponse = {
  mac_address: "aa:bb:cc:dd:ee:ff",
  status: 0,
  message: "Successfully retrieved upstream ATDMA channel statistics",
  system_description: {
    VENDOR: "CommScope",
    MODEL: "CM8200A",
    HW_REV: "3",
    SW_REV: "9.1.103",
    BOOTR: "2.4.18",
  },
  results: {
    dwr_window_check: {
      dwr_warning_db: 6,
      dwr_violation_db: 12,
      spread_db: 2.4,
      channel_count: 4,
      min_power_dbmv: 42.5,
      max_power_dbmv: 44.9,
      is_warning: false,
      is_violation: false,
      extreme_channel_ids: [3, 5],
    },
    entries: [
      {
        index: 1,
        channel_id: 3,
        entry: {
          docsIfUpChannelId: 3,
          docsIfUpChannelFrequency: 23700000,
          docsIfUpChannelWidth: 6400000,
          docsIf3CmStatusUsTxPower: 42.5,
          docsIf3CmStatusUsIsMuted: false,
          docsIfUpChannelPreEqEnable: true,
          docsIfUpChannelStatus: 1,
          docsIf3CmStatusUsT3Timeouts: 2,
          docsIf3CmStatusUsT4Timeouts: 0,
          docsIf3CmStatusUsT3Exceededs: 0,
          docsIf3CmStatusUsRangingAborteds: 0,
          docsIf3CmStatusUsModulationType: 2,
          docsIfUpChannelSlotSize: 6,
          docsIfUpChannelTxTimingOffset: 64,
          docsIf3CmStatusUsRangingStatus: 4,
          docsIfUpChannelType: 1,
        },
      },
      {
        index: 2,
        channel_id: 4,
        entry: {
          docsIfUpChannelId: 4,
          docsIfUpChannelFrequency: 30100000,
          docsIfUpChannelWidth: 6400000,
          docsIf3CmStatusUsTxPower: 43.1,
          docsIf3CmStatusUsIsMuted: false,
          docsIfUpChannelPreEqEnable: true,
          docsIfUpChannelStatus: 1,
          docsIf3CmStatusUsT3Timeouts: 1,
          docsIf3CmStatusUsT4Timeouts: 0,
          docsIf3CmStatusUsT3Exceededs: 0,
          docsIf3CmStatusUsRangingAborteds: 0,
          docsIf3CmStatusUsModulationType: 2,
          docsIfUpChannelSlotSize: 6,
          docsIfUpChannelTxTimingOffset: 61,
          docsIf3CmStatusUsRangingStatus: 4,
          docsIfUpChannelType: 1,
        },
      },
      {
        index: 3,
        channel_id: 5,
        entry: {
          docsIfUpChannelId: 5,
          docsIfUpChannelFrequency: 36500000,
          docsIfUpChannelWidth: 6400000,
          docsIf3CmStatusUsTxPower: 44.9,
          docsIf3CmStatusUsIsMuted: false,
          docsIfUpChannelPreEqEnable: true,
          docsIfUpChannelStatus: 1,
          docsIf3CmStatusUsT3Timeouts: 4,
          docsIf3CmStatusUsT4Timeouts: 0,
          docsIf3CmStatusUsT3Exceededs: 1,
          docsIf3CmStatusUsRangingAborteds: 0,
          docsIf3CmStatusUsModulationType: 2,
          docsIfUpChannelSlotSize: 6,
          docsIfUpChannelTxTimingOffset: 57,
          docsIf3CmStatusUsRangingStatus: 4,
          docsIfUpChannelType: 1,
        },
      },
      {
        index: 4,
        channel_id: 6,
        entry: {
          docsIfUpChannelId: 6,
          docsIfUpChannelFrequency: 42900000,
          docsIfUpChannelWidth: 6400000,
          docsIf3CmStatusUsTxPower: 42.8,
          docsIf3CmStatusUsIsMuted: false,
          docsIfUpChannelPreEqEnable: false,
          docsIfUpChannelStatus: 1,
          docsIf3CmStatusUsT3Timeouts: 0,
          docsIf3CmStatusUsT4Timeouts: 0,
          docsIf3CmStatusUsT3Exceededs: 0,
          docsIf3CmStatusUsRangingAborteds: 0,
          docsIf3CmStatusUsModulationType: 2,
          docsIfUpChannelSlotSize: 6,
          docsIfUpChannelTxTimingOffset: 66,
          docsIf3CmStatusUsRangingStatus: 4,
          docsIfUpChannelType: 1,
        },
      },
    ],
  },
};
