import type { If31UsOfdmaChannelStatsResponse } from "@/types/api";

export const singleIf31UsOfdmaChannelStatsFixture: If31UsOfdmaChannelStatsResponse = {
  mac_address: "aa:bb:cc:dd:ee:ff",
  status: 0,
  message: "Pre-check completed successfully",
  system_description: {
    VENDOR: "CommScope",
    MODEL: "DOCSIS31-CM",
    HW_REV: "2",
    SW_REV: "10.2.1",
    BOOTR: "3.0.4",
  },
  results: [
    {
      index: 1,
      channel_id: 193,
      entry: {
        docsIf31CmUsOfdmaChanChannelId: 193,
        docsIf31CmUsOfdmaChanConfigChangeCt: 4,
        docsIf31CmUsOfdmaChanSubcarrierZeroFreq: 17600000,
        docsIf31CmUsOfdmaChanFirstActiveSubcarrierNum: 940,
        docsIf31CmUsOfdmaChanLastActiveSubcarrierNum: 2980,
        docsIf31CmUsOfdmaChanNumActiveSubcarriers: 2041,
        docsIf31CmUsOfdmaChanSubcarrierSpacing: 50000,
        docsIf31CmUsOfdmaChanCyclicPrefix: 256,
        docsIf31CmUsOfdmaChanRollOffPeriod: 128,
        docsIf31CmUsOfdmaChanNumSymbolsPerFrame: 36,
        docsIf31CmUsOfdmaChanTxPower: 39.2,
        docsIf31CmUsOfdmaChanPreEqEnabled: true,
        docsIf31CmStatusOfdmaUsT3Timeouts: 0,
        docsIf31CmStatusOfdmaUsT4Timeouts: 0,
        docsIf31CmStatusOfdmaUsRangingAborteds: 0,
        docsIf31CmStatusOfdmaUsT3Exceededs: 0,
        docsIf31CmStatusOfdmaUsIsMuted: false,
        docsIf31CmStatusOfdmaUsRangingStatus: "stationMaintenance",
      },
    },
    {
      index: 2,
      channel_id: 194,
      entry: {
        docsIf31CmUsOfdmaChanChannelId: 194,
        docsIf31CmUsOfdmaChanConfigChangeCt: 7,
        docsIf31CmUsOfdmaChanSubcarrierZeroFreq: 17600000,
        docsIf31CmUsOfdmaChanFirstActiveSubcarrierNum: 3300,
        docsIf31CmUsOfdmaChanLastActiveSubcarrierNum: 5640,
        docsIf31CmUsOfdmaChanNumActiveSubcarriers: 2341,
        docsIf31CmUsOfdmaChanSubcarrierSpacing: 50000,
        docsIf31CmUsOfdmaChanCyclicPrefix: 256,
        docsIf31CmUsOfdmaChanRollOffPeriod: 128,
        docsIf31CmUsOfdmaChanNumSymbolsPerFrame: 36,
        docsIf31CmUsOfdmaChanTxPower: 40.1,
        docsIf31CmUsOfdmaChanPreEqEnabled: true,
        docsIf31CmStatusOfdmaUsT3Timeouts: 2,
        docsIf31CmStatusOfdmaUsT4Timeouts: 0,
        docsIf31CmStatusOfdmaUsRangingAborteds: 1,
        docsIf31CmStatusOfdmaUsT3Exceededs: 0,
        docsIf31CmStatusOfdmaUsIsMuted: false,
        docsIf31CmStatusOfdmaUsRangingStatus: "stationMaintenance",
      },
    },
    {
      index: 3,
      channel_id: 195,
      entry: {
        docsIf31CmUsOfdmaChanChannelId: 195,
        docsIf31CmUsOfdmaChanConfigChangeCt: 11,
        docsIf31CmUsOfdmaChanSubcarrierZeroFreq: 17600000,
        docsIf31CmUsOfdmaChanFirstActiveSubcarrierNum: 6000,
        docsIf31CmUsOfdmaChanLastActiveSubcarrierNum: 7880,
        docsIf31CmUsOfdmaChanNumActiveSubcarriers: 1881,
        docsIf31CmUsOfdmaChanSubcarrierSpacing: 50000,
        docsIf31CmUsOfdmaChanCyclicPrefix: 512,
        docsIf31CmUsOfdmaChanRollOffPeriod: 128,
        docsIf31CmUsOfdmaChanNumSymbolsPerFrame: 40,
        docsIf31CmUsOfdmaChanTxPower: 41.7,
        docsIf31CmUsOfdmaChanPreEqEnabled: false,
        docsIf31CmStatusOfdmaUsT3Timeouts: 5,
        docsIf31CmStatusOfdmaUsT4Timeouts: 1,
        docsIf31CmStatusOfdmaUsRangingAborteds: 1,
        docsIf31CmStatusOfdmaUsT3Exceededs: 2,
        docsIf31CmStatusOfdmaUsIsMuted: true,
        docsIf31CmStatusOfdmaUsRangingStatus: "periodicRanging",
      },
    },
  ],
};
