// Mirrors PyPNM's PnmFileType enum names so the WebUI does not depend on ad hoc string literals.
export enum PnmFileType {
  SYMBOL_CAPTURE = "SYMBOL_CAPTURE",
  OFDM_CHANNEL_ESTIMATE_COEFFICIENT = "OFDM_CHANNEL_ESTIMATE_COEFFICIENT",
  DOWNSTREAM_CONSTELLATION_DISPLAY = "DOWNSTREAM_CONSTELLATION_DISPLAY",
  RECEIVE_MODULATION_ERROR_RATIO = "RECEIVE_MODULATION_ERROR_RATIO",
  DOWNSTREAM_HISTOGRAM = "DOWNSTREAM_HISTOGRAM",
  UPSTREAM_PRE_EQUALIZER_COEFFICIENTS = "UPSTREAM_PRE_EQUALIZER_COEFFICIENTS",
  UPSTREAM_PRE_EQUALIZER_COEFFICIENTS_LAST_UPDATE = "UPSTREAM_PRE_EQUALIZER_COEFFICIENTS_LAST_UPDATE",
  OFDM_FEC_SUMMARY = "OFDM_FEC_SUMMARY",
  SPECTRUM_ANALYSIS = "SPECTRUM_ANALYSIS",
  OFDM_MODULATION_PROFILE = "OFDM_MODULATION_PROFILE",
  LATENCY_REPORT = "LATENCY_REPORT",
  CM_SPECTRUM_ANALYSIS_SNMP_AMP_DATA = "CM_SPECTRUM_ANALYSIS_SNMP_AMP_DATA",
}

export function parsePnmFileType(value: string): PnmFileType | null {
  return Object.values(PnmFileType).includes(value as PnmFileType) ? (value as PnmFileType) : null;
}
