export const DEFAULT_HISTOGRAM_SAMPLE_DURATION_SECONDS = 10;
export const DEFAULT_SCQAM_CODEWORD_SAMPLE_TIME_SECONDS = 5;
export const DEFAULT_CONSTELLATION_DISPLAY_CROSS_HAIR = true;
export const DEFAULT_CONSTELLATION_MODULATION_ORDER_OFFSET = 0;
export const DEFAULT_CONSTELLATION_SAMPLE_SYMBOL_COUNT = 8_192;
