import type { DsScqamChannelStatsResponse } from "@/types/api";

export const singleDsScqamChannelStatsFixture: DsScqamChannelStatsResponse = {
  mac_address: "aa:bb:cc:dd:ee:ff",
  status: 0,
  message: "Successfully retrieved downstream SC-QAM channel stats",
  system_description: {
    VENDOR: "CommScope",
    MODEL: "CM8200A",
    HW_REV: "3",
    SW_REV: "9.1.103",
    BOOTR: "2.4.18",
  },
  results: [
    {
      index: 1,
      channel_id: 21,
      entry: {
        docsIfDownChannelId: 21,
        docsIfDownChannelFrequency: 555000000,
        docsIfDownChannelWidth: 6000000,
        docsIfDownChannelModulation: "qam256",
        docsIfDownChannelInterleave: "taps32Increment4",
        docsIfDownChannelPower: 1.2,
        docsIfSigQUnerroreds: 1432000,
        docsIfSigQCorrecteds: 122,
        docsIfSigQUncorrectables: 2,
        docsIfSigQMicroreflections: 18,
        docsIfSigQExtUnerroreds: 4523001,
        docsIfSigQExtCorrecteds: 187,
        docsIfSigQExtUncorrectables: 4,
        docsIf3SignalQualityExtRxMER: 38.6,
      },
    },
    {
      index: 2,
      channel_id: 22,
      entry: {
        docsIfDownChannelId: 22,
        docsIfDownChannelFrequency: 561000000,
        docsIfDownChannelWidth: 6000000,
        docsIfDownChannelModulation: "qam256",
        docsIfDownChannelInterleave: "taps32Increment4",
        docsIfDownChannelPower: 0.8,
        docsIfSigQUnerroreds: 1399000,
        docsIfSigQCorrecteds: 214,
        docsIfSigQUncorrectables: 6,
        docsIfSigQMicroreflections: 24,
        docsIfSigQExtUnerroreds: 4482300,
        docsIfSigQExtCorrecteds: 241,
        docsIfSigQExtUncorrectables: 9,
        docsIf3SignalQualityExtRxMER: 37.9,
      },
    },
    {
      index: 3,
      channel_id: 23,
      entry: {
        docsIfDownChannelId: 23,
        docsIfDownChannelFrequency: 567000000,
        docsIfDownChannelWidth: 6000000,
        docsIfDownChannelModulation: "qam256",
        docsIfDownChannelInterleave: "taps32Increment4",
        docsIfDownChannelPower: 1.5,
        docsIfSigQUnerroreds: 1456000,
        docsIfSigQCorrecteds: 91,
        docsIfSigQUncorrectables: 1,
        docsIfSigQMicroreflections: 12,
        docsIfSigQExtUnerroreds: 4608801,
        docsIfSigQExtCorrecteds: 125,
        docsIfSigQExtUncorrectables: 2,
        docsIf3SignalQualityExtRxMER: 39.1,
      },
    },
  ],
};
